#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: $0 init|drop"
  exit 1
fi

if [ "$1" == "init" ]; then
  su - postgres -c "psql -w -f /home/dimara/keda/db_init.psql"
  python manage.py syncdb
  python manage.py loaddata reception/fixtures/*
fi

if [ "$1" == "drop" ]; then
  su - postgres -c "psql -w -c 'DROP DATABASE KEDA;'"
  su - postgres -c "psql -w -c 'DROP USER keda;'"
fi
