# Generated by Django 2.2.28 on 2024-03-24 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Α', 'Α'), ('Ι', 'Ι'), ('Β', 'Β'), ('Ζ', 'Ζ'), ('Ε', 'Ε'), ('Μ1', 'Μ1'), ('Μ2', 'Μ2'), ('Μ3', 'Μ3'), ('Μ4', 'Μ4'), ('Μ5', 'Μ5'), ('Μ3Ε', 'Μ3Ε')], max_length=5, verbose_name='Area')),
                ('no', models.CharField(max_length=5, verbose_name='Number')),
                ('rooms', models.IntegerField(blank=True, default=1, null=True, verbose_name='Rooms')),
                ('double', models.IntegerField(choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')], default=0, verbose_name='Double Beds')),
                ('single', models.IntegerField(choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')], default=2, verbose_name='Single Beds')),
                ('bunk', models.IntegerField(choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')], default=0, verbose_name='Bunk Beds')),
                ('ranking', models.IntegerField(blank=True, choices=[(1, 'Low'), (3, 'Medium'), (5, 'High')], default=None, null=True, verbose_name='Quality Ranking')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Description')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='Ranking')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Period')),
                ('start', models.DateField(verbose_name='Starting Date')),
                ('end', models.DateField(verbose_name='Ending Date')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('ident', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(choices=[('ΕΣ', 'ΕΣ'), ('ΠΝ', 'ΠΝ'), ('ΠΑ', 'ΠΑ')], default='ΠΑ', max_length=5, verbose_name='Force')),
                ('rank', models.CharField(max_length=20, verbose_name='Rank')),
                ('short', models.CharField(max_length=10, verbose_name='Rank (abbreviation)')),
                ('level', models.IntegerField(blank=True, default=0, null=True, verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('internal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Internal Number')),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reception.Person')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('speciality', models.CharField(blank=True, max_length=20, null=True, verbose_name='Speciality')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='military_persons', to='reception.Rank')),
            ],
            bases=('reception.person',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Plate')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=20, null=True, verbose_name='Model')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='reception.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='Check In')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Check Out')),
                ('agent', models.IntegerField(blank=True, choices=[(0, 'ΓΕΑ/Β3'), (1, 'ΕΑ'), (2, 'Μ.Υ'), (3, 'ΔΚΤΗΣ'), (4, 'ΥΔΚΤΗΣ'), (5, 'ΑΣΦΑΛΕΙΑ'), (6, 'RECEPTION'), (7, 'ΓΕΕΘΑ')], null=True, verbose_name='Agent')),
                ('persons', models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine')], default=1, null=True, verbose_name='Persons')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Canceled'), (3, 'Checked OUT'), (4, 'Unknown')], null=True, verbose_name='Status')),
                ('res_type', models.IntegerField(blank=True, choices=[(0, 'ΤΑΚΤΙΚΟΣ'), (1, 'ΠΑΡ/ΣΤΗΣ'), (2, 'ΟΣΣΕΑΥ'), (3, 'ΜΟΝΑΔΑ'), (4, 'ΣΧΟΛΕΙΑ'), (5, 'CLIMS'), (6, 'ΑΓΑΜΩΝ'), (7, 'ΑΠΟΣ/ΝΟΙ'), (8, 'ΑΛΛΟ')], null=True, verbose_name='Type')),
                ('telephone', models.BooleanField(default=False, verbose_name='Telephone')),
                ('book_ref', models.IntegerField(blank=True, null=True, verbose_name='No')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('appartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reception.Appartment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reception.MilitaryPerson')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('no', models.CharField(max_length=10, verbose_name='No')),
                ('euro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Euro')),
                ('pending', models.BooleanField(default=False, verbose_name='Pending')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='reception.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('AC', 'A/C'), ('TV', 'TV'), ('DIRTY', 'Πολύ βρώμικο, Θέλει καθάρισμα, κλπ.'), ('ELECTRICAL', 'Φώτα, Μπρίζες, κλπ.'), ('HYDRAVLICS', 'Διαρροές, τουαλέτες, Θερμοσίφωνες, κλπ.'), ('DOORS', 'Πόρτες, Κλειδαριές, Παράθυρα, κλπ.'), ('EQUIPMENT', 'Χαλασμένος/Ελλιπής εξοπλισμός, etc.'), ('WALLS', 'Θέλει βάψιμο, χαλασμένο ταβάνι/τοίχοι, etc.'), ('OTHER', 'Άλλου είδους βλάβη')], max_length=30, verbose_name='Tag')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Further Info')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('fixed', models.BooleanField(default=False, verbose_name='Fixed')),
                ('appartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='reception.Appartment')),
                ('notified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile Phone')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telephone')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Address')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='reception.Person')),
            ],
        ),
        migrations.AddField(
            model_name='appartment',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appartments', to='reception.Category'),
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reception.Person')),
                ('relationship', models.CharField(blank=True, choices=[('ΥΙΟΣ', 'ΥΙΟΣ'), ('ΚΟΡΗ', 'ΚΟΡΗ'), ('ΠΑΤΕΡΑΣ', 'ΠΑΤΕΡΑΣ'), ('ΜΗΤΕΡΑ', 'ΜΗΤΕΡΑ'), ('ΣΥΖΥΓΟΣ', 'ΣΥΖΥΓΟΣ'), ('ΑΝΗΨΙΑ', 'ΑΝΗΨΙΑ'), ('ΑΔΕΡΦΙΑ', 'ΑΔΕΡΦΙΑ'), ('ΕΓΓΟΝΙΑ', 'ΕΓΓΟΝΙΑ'), ('ΝΥΦΗ', 'ΝΥΦΗ'), ('ΓΑΜΠΡΟΣ', 'ΓΑΜΠΡΟΣ'), ('ΠΕΘΕΡΟΣ', 'ΠΕΘΕΡΟΣ'), ('ΠΕΘΕΡΑ', 'ΠΕΘΕΡΑ')], max_length=30, null=True, verbose_name='Relationship')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='reception.Person')),
            ],
            bases=('reception.person',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('militaryperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reception.MilitaryPerson')),
                ('category', models.CharField(blank=True, choices=[('ΟΡΓ', 'ΟΡΓΑΝΙΚΟΣ'), ('ΑΠΟ', 'ΑΠΟΣΠΑΣΜΕΝΟΣ')], max_length=20, null=True, verbose_name='Category')),
                ('extra', models.CharField(blank=True, max_length=25, null=True, verbose_name='Extra Info')),
                ('power', models.BooleanField(default=True, verbose_name='In Unit-Power')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='reception.Unit')),
            ],
            bases=('reception.militaryperson',),
        ),
    ]
